tap "github/gh"
tap "homebrew/cask-fonts"
cask "font-fira-code"
brew "openssl"
brew "sqlite"
brew "git"
brew "gh"
brew "gnupg"
brew "haskell-stack"
brew "mas"
brew "thefuck"
brew "shellcheck"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "font-source-code-pro"
cask "google-chrome"
cask "visual-studio-code"
mas "DigiDoc4 Client", id: 1370791134
mas "Grammarly for Safari", id: 1462114288
# mas "Keynote"
# mas "Numbers"
# mas "Pages"
mas "Xcode", id: 4977998350